Repository plusserver/docs, pull requests merged in 2024-07, with the labels that each got.

#124 Headlines without underlining
  assets/scss/_styles_project.scss
Labels: enhancement

#121 Update postcss version to 8.4.39
  package-lock.json
  package.json
Labels: housekeeping

#122 Improve and clean up hugo.toml
  hugo.toml
Labels: enhancement, housekeeping

#123 Modify image guidelines
  guidelines/20-styling.md
  guidelines/30-markdown.md
  layouts/shortcodes/img.html
Labels: enhancement, housekeeping

#125 Add pluscloudv/reference/vGPU
  content/de/compute/pluscloudvmware/reference/_index.md
  content/de/compute/pluscloudvmware/reference/vgpu/_index.md
  content/en/compute/pluscloudvmware/reference/_index.md
  content/en/compute/pluscloudvmware/reference/vgpu/_index.md
Labels: documentation
